### ISSUE TITLE
Streaming Issue

### ISSUE THREAD

**Issue by TheSPD** [saurabh-deochake/Topik#5]
Getting this error in Streaming

Traceback (most recent call last):
  File "streaming.py", line 52, in <module>
    main()
  File "streaming.py", line 45, in main
    stream.filter(locations = nj)
  File "/usr/lib/python2.7/site-packages/tweepy/streaming.py", line 445, in filter
    self._start(async)
  File "/usr/lib/python2.7/site-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/usr/lib/python2.7/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry '723723307758047232' for key 'PRIMARY'")

**Comment by TheSPD** [comment]
Fixed in the new version
